Movie_App/urls.py
from django.urls  import path
from . import views
app_name="Movie_App"
urlpatterns =[
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.movie_add,name='movie_add'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/', views.delete, name='delete')
]

Movie_Project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('Movie_App.urls')),
]

Movie_App/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

Movie_App/forms.py
from django import forms
from .models import movie

class movieform(forms.ModelForm):
    class Meta:
        model=movie
        fields=['name','desc','year','img']

Movie_App/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import movie
from .forms import forms, movieform


# Create your views here.
def index(request):
    Movie=movie.objects.all()

    context={
        "movie_list":Movie
    }
    return render(request,'index.html',context)

def detail(request,movie_id):
    Movie=movie.objects.get(id=movie_id)
    return render(request,"detail.html",{'MOVIE':Movie})

def movie_add(request):
    if request.method=='POST':
        name=request.POST.get('name')
        desc=request.POST.get('desc')
        year=request.POST.get('year')
        img=request.FILES['img']

        movie2=movie(name=name,desc=desc,year=year,img=img)
        movie2.save()

    return render(request,'add.html')


def update(request,id):
    Movie=movie.objects.get(id=id)
    form=movieform(request.POST or None ,request.FILES,instance=Movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'movie':Movie,'form':form})

def delete(request,id):
    if request.method=='POST':
        Movie=movie.objects.get(id=id)
        Movie.delete()
        return redirect('/')
    return render(request,'delete.html')

templates/add.html
{% extends 'base.html'%}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter your movie name">
        <input type="text" name="desc" placeholder="Enter your movie description">
    <input type="text" name="year" placeholder="Enter your movie year">
    <input type="file" name="img">
    <input type="submit">

</form>

</body>
</html>
    {% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
    <a class="navbar-band" href="#">
        Online Movie Store
    </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/delete.html
<form method="POST" >
    {% csrf_token %}
    Are You Want To Delete This Movie..?
    <input type="submit">
</form>

templates/detail.html
{% extends 'base.html'%}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{MOVIE.img.url}}" width="400" height="250">
        </div>


        <h2>{{MOVIE.name}}</h2><br>
        <h4>{{MOVIE.desc}}</h4><br>
        <h1>{{MOVIE.year}}<h1><br>
<a class="btn btn-warning" href="{% url 'Movie_App:update' MOVIE.id %}">Update</a>
<a class="btn btn-danger" href="{% url 'Movie_App:delete' MOVIE.id %}">Delete</a>
   </div>
</div>
{% endblock %}

templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">

</form>

templates/index.html
{% extends 'base.html'%}
{% block body %}
<div class="container">
    <div class="row">

        {% for i in movie_list %}
        <div class="col-md-3">
            <div class="card" style="width: 18rem;">
  <img  src="{{i.img.url}}" class="card-img-top" alt="Card image cap" width="200px" height="150px">
  <div class="card-body">
    <h5 class="card-title">{{i.name.url}}</h5>
    <p class="card-text">{{i.desc.url}}</p>
    <a href="{% url 'Movie_App:detail' i.id %}" class="btn btn-warning">View Details</a>
  </div>
</div>
        </div>
        {% endfor %}
    </div>
</div>





    {% endblock %}